# vich_uploader:
#   db_driver: orm
#   mappings:
#     piece_jointe:
#       uri_prefix: /uploads/pieces_jointes
#       upload_destination: "%kernel.project_dir%/public/uploads/pieces_jointes"
#       namer: Vich\UploaderBundle\Naming\UniqidNamer
#       inject_on_load: false
#       delete_on_update: true
#       delete_on_remove: true
vich_uploader:
  db_driver: orm
  mappings:
    piece_jointe:
      uri_prefix: /uploads/pieces_jointes
      upload_destination: "%kernel.project_dir%/public/uploads/pieces_jointes"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
  #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
